laracord/framework

- composer.json
- src/Commands/AbstractCommand.php
- src/Commands/Command.php
- src/Commands/Components/Message.php
- src/Commands/Contracts/Command.php
- src/Commands/Contracts/SlashCommand.php
- src/Commands/HelpCommand.php
- src/Commands/SlashCommand.php
- src/Console/Commands/MakeSlashCommand.php
- src/Console/Commands/ModelMakeCommand.php
- src/Console/Commands/stubs/command.stub
- src/Console/Commands/stubs/model.stub
- src/Console/Commands/stubs/slash-command.stub
- src/Console/Concerns/WithLog.php
- src/Laracord.php
- src/LaracordServiceProvider.php
- ➕ Add `react/async` to the project
- ✨ Implement a simplified `make:model` command (Fixes #9)
- 🎨 Simplify the Command docblocks
- 🎨 Split the Command class into an AbstractCommand class
- 🧑‍💻 Add warn and error override helpers to the `WithLog` trait
- ✨ Add slash command support (Fixes #2)
- ✨ Add user messaging support to the message component (Fixes #10)
- 🎨 Validate the command prefix
> ✨ Add slash command support (Fixes #2)

- src/Laracord.php
- 🧑‍💻 Remove unnecessary command conditional during boot (Fixes #24)
- 🩹 Fix invalid variable in `unregisterSlashCommand` failed warning
> 🧑‍💻 Remove unnecessary command conditional during boot (Fixes #24)

- composer.json
- config/app.php
- config/discord.php
- src/Console/Commands/AdminCommand.php
- src/Console/Commands/ControllerMakeCommand.php
- src/Console/Commands/TokenMakeCommand.php
- src/Console/Commands/stubs/controller.stub
- src/Console/Concerns/ResolvesUser.php
- src/Http/Controllers/Controller.php
- src/Http/Kernel.php
- src/Http/Middleware/EnsureTokenIsValid.php
- src/Http/Middleware/TrimStrings.php
- src/Http/Server.php
- src/Laracord.php
- src/LaracordServiceProvider.php
- src/Logging/Logger.php
This is an initial HTTP server implementation for `react/http` with full Laravel routing support. This will allow you to create webhooks and an API to interact with your bot.
If you would like to help test this PR as-is, you can try it out with the following:
```sh
composer create-project laracord/laracord
cd laracord
composer require laracord/framework:dev-feat/21
```
**app/Bot.php**
```php
<?php
namespace App;
use Illuminate\Support\Facades\Route;
use Laracord\Laracord;
class Bot extends Laracord
{
/**
* The HTTP routes.
*/
public function routes(): void
{
Route::get('/', fn () => collect(Route::getRoutes()->getRoutes())->map(fn ($route) => $route->uri));
Route::get('/commands', fn () => collect($this->registeredCommands)->map(fn ($command) => [
'signature' => $command->getSignature(), …
```
> ✨ Implement an optional `react/http` server (Fixes #21)

- composer.json
- config/app.php
- config/cache.php
- config/filesystems.php
- config/session.php
- config/view.php
- src/Console/Commands/BootCommand.php
- src/Console/Commands/KeyGenerateCommand.php
- src/HasLaracord.php
- src/Http/Controllers/Controller.php
- src/Http/Kernel.php
- src/Http/Providers/RouteServiceProvider.php
- src/Http/Server.php
- src/Laracord.php
- src/LaracordServiceProvider.php
This PR finalizes the ReactPHP HTTP server/routing implementation adding support for [Livewire 3](https://livewire.laravel.com/).
Generate an application key:
```sh
$ php laracord key:generate
```
Install Livewire:
```sh
$ composer require livewire/livewire
```
Add the Livewire provider to `config/app.php`:
```php
/*
|--------------------------------------------------------------------------
| Autoloaded Service Providers
|--------------------------------------------------------------------------
|
| The service providers listed here will be automatically loaded on the
| request to your application. Feel free to add your own services to
| this array to grant expanded functionality to your applications.
|
*/
'providers' => [
App\Providers\BotServiceProvider::class, …
```
> ✨ Add Livewire support to the HTTP server

- src/Discord/Message.php
- src/Http/Server.php
- src/Laracord.php
This adds basic support for input stream commands to stop, restart, and invite the bot.
- ✨ Add input/output stream support (Fixes #41) 
- ✨ Add generic input stream commands `stop`, `restart`, `invite`, `commands`, and `?`
- ✨ Add file support to the Message component 
- 🧑‍💻 Create methods to shutdown and restart Laracord
- 🧑‍💻 Add support for forcefully displaying the invite link
- 🧑‍💻 Add registered route count to the boot status
- 🧑‍💻 Add a `httpServer()` getter method
- 🎨 Minor code improvements
- 🧑‍💻 Add a shutdown() method to the HTTP server 
- 🎨 Add missing `bot` properties
- 🎨 Improve usage of the `bot` property
- 🩹 Fix typo in `httpServer` property return type
> ✨ Add input/output stream support

- src/Discord/Message.php
- 🎨 Improve message button style support
- 🎨 Improve message file method naming conventions
> 🎨 Improve message button style support

- src/Discord/Message.php
- 🧑‍💻 Change the Message `send` and `sendTo` return type to a promise
- 🎨 Log a console error instead of exception when passed an invalid user
> 🧑‍💻 Change the Message `send` and `sendTo` return type to a promise

- src/Commands/SlashCommand.php
- src/Console/Commands/stubs/slash-command.stub
- src/Discord/Message.php
- ✨ Add default permission support to slash commands 
- ✨ Add option parsing to slash commands
- 🧑‍💻 Add `clearFields()` and `clearButtons()` to the Message builder
- 🧑‍💻 Add carbon support to `timestamp()`
- 🧑‍💻 Default to current time when nothing is passed to `timestamp()`
> ✨ Add default permission support & option parsing to slash commands

- src/Discord/Message.php
- src/Laracord.php
- 🧑‍💻 Allow passing `disabled` to message buttons 
- 🧑‍💻 Prepend `set` to the button option keys
- 🧑‍💻 Add a `getCommand()` method to easily obtain a command instance
> 🧑‍💻 Allow passing disabled to message buttons 

- src/Laracord.php
- 🥅 Catch and log command, service, and event throwables to console during registration and handling
- ⏪️ Revert to generic Artisan tables for compatibility
- 🧑‍💻 Run `afterBoot()` before showing boot messages
- 🎨 Add missing return type to `getLoop()`
> 🥅 Improve error handling

- src/Commands/SlashCommand.php
This commit introduces a new method, `getOptionValue`, in our command handling class. The method simplifies retrieving the 'value' key directly from the command options. It helps avoid repetitive array access code and makes our option parsing cleaner. The method assumes options are stored as arrays with a 'value' key and handles the absence of such a key gracefully by returning a default value if specified or null otherwise.
> Add method to fetch option 'value' key from command options

- src/Commands/AbstractCommand.php
- src/Commands/Command.php
- src/Console/Commands/stubs/command.stub
- src/Console/Commands/stubs/slash-command.stub
- src/Discord/Message.php
- src/Laracord.php
This PR adds persistent interaction routing allowing for easy persistence and handling of interactions such as button clicks.
It is based on Laravel routing and allows for passing parameters such as `{id}` and making them optional using a `?` like `{id?}`. All parameters should be passed using `:` instead of `/`. 
All routes are prefixed with the command name behind the scenes to remain unique.
It is hopefully pretty straight forward to use, see the following example:
```php
/**
* Handle the command.
*/
public function handle($message, $args)
{
return $this
->message()
->title('Hello')
->content('Hello world!')
->button('👋', route: 'wave')
->button('Test', route: 'wave:12345')
->send($message);
}
/**
* The command interaction routes.
*/
public function interactions(): array
{
return [ …
```
> ✨ Add persistent interaction routing support to commands (Fixes #79)

- src/Discord/Message.php
This adds a `->webhook()` method that will send messages in a channel through a webhook to allow for further customization such as username & avatar.
It can be used in two ways:
When passing no argument, Laracord will attempt to create a webhook in the destination channel with the same name as the bot. It will then re-use that webhook when sending webhook messages in that channel in the future:
```php
$this
->message()
->username('Example')
->avatar('https://example.com/avatar.png')
->content('Hello world!')
->webhook()
->send($channel);
```
The second way would be to pass a webhook URL of which already exists for the destination channel:
```php
$this
->message()
->username('Example')
->avatar('https://example.com/avatar.png')
->content('Hello world!') …
```
> ✨ Add webhook support to Messages (Fixes #52)

- README.md
- src/Commands/AbstractCommand.php
- src/Commands/Command.php
- src/Commands/HelpCommand.php
- src/Commands/SlashCommand.php
- src/Discord/Message.php
- src/Events/Event.php
- src/Laracord.php
- ✨ Allow restricting a chat command to a specific guild (Fixes #70)
- 🔒 Filter guild-specific commands when using `!help `
- 🎨 Sort the `!help` commands by name
- 🎨 Clean up `Str::toString()` usage
- 🎨 Ensure that `Message::$color` is set as a string
- ✨ Add a `status` command to the bot stdin 
- 🎨 Add missing type on the `loop` property
- 🧑‍💻 Abstract the logger into a method to make it easier to override
- 📝 Update the features list
> ✨ Allow restricting a chat command to a specific guild (Fixes #70)

- src/Commands/AbstractCommand.php
- src/Discord/Concerns/HasModal.php
- src/Discord/Modal.php
This adds native modal support to Laracord. By default, the `HasModal` trait is available on commands making `$this->modal()` usable.
```php
$this
->modal('Send a Message')
->text('Title', placeholder: 'Enter a title...', minLength: 2, maxLength: 32, required: true)
->paragraph('Content', placeholder: 'Enter a message...', minLength: 5, maxLength: 256, required: true)
->submit(fn (Interaction $interaction, Collection $components) => $this->handleModal($interaction, $components))
->show($interaction);
```
> ✨ Add native interaction modal support

- src/Concerns/CanAsync.php
- src/Laracord.php
- src/LaracordServiceProvider.php
This adds async macros to common methods inside of `Cache`, `Http` and `Storage` facades.
```php
Cache::getAsync(string $key);
Cache::putAsync(string $key, mixed $value, int $seconds);
Cache::rememberAsync(string $key, int $seconds, callable $callback);
Cache::rememberForeverAsync(string $key, callable $callback);
Http::getAsync(string $url, array|string|null $query = []);
Http::postAsync(string $url, array $data = []);
File::getAsync(string $path);
File::putAsync(string $path, mixed $contents);
Storage::getAsync(string $path);
Storage::putAsync(string $path, mixed $contents);
```
- ✨ Add async macros for common methods to the `Cache`, `Http` and `Storage` facades
- ✨ Create an `CanAsync` trait to easily perform async tasks in the event loop
> ✨ Add async macros to common Facade methods

- src/Commands/AbstractCommand.php
- src/Commands/Command.php
- src/Commands/SlashCommand.php
- src/Laracord.php
This PR adds a better syntax and the possibility to handle autocomplete within Slash Commands
It provides 3 ways of syntax
Using a choice class
```php
public function autocomplete(): array
{
return [
'attribute' => fn ($interaction, $value) => [
Choice::new($this->discord(), 'attribute', 'attribute'),
],
];
}
```
Using key value pairs
```php
public function autocomplete(): array
{
return [
'attribute' => fn ($interaction, $value) => [
'attribute' => 'attribute',
],
];
}
```
Using just an array of strings, with this option the autocomplete handler takes the liberty of using the string to create a name for the choice slugified, this last option might be too opinionated but let me know your thoughts.
```php
public function autocomplete(): array
{
return [
'attribute' => fn ($interaction, …
```
> ✨Native option autocomplete support 

- src/Concerns/CanAsync.php
The previous implementation of the async method within CanAsync referenced itself, hence causing an infinite loop
> 🩹 Fix CanAsync infinite loop

- src/Discord/Message.php
This PR fixes an issue with the editOrReply functionality. 
If we use the interaction->user->id it will always be false compared to the discord id, this PR updates it to use the message user id instead which lets the message be edited.
> Use the message user id instead of the interaction user id

- src/Http/Middleware/AuthorizeToken.php
Currently, if we define the following HTTP route:
```php
Route::middleware('api')->group(function () {
Route::post('/test', ExampleController::class);
});
```
we won't be able to access it if we send a POST request to:
```
http://localhost:8080/test?token=mytoken
```
because internally, Symfony [clears the query parameters](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/HttpFoundation/Request.php#L337-L353) for non GET requests.
> 🩹 Fix token authorization

- src/Http/Server.php
The `?->` operator can't be used if the method doesn't exist (which will be the case if the response is not a file):
```php
use Illuminate\Http\Response;
return new Response('', Response::HTTP_NO_CONTENT); // Empty response
```
> 🩹 Fix bad method call exception in the `Server` class

- composer.json
- config/database.php
- src/Discord/Message.php
- src/Laracord.php
- ✨ Add attachment support to the message builder 
- ✨ Add sticker support to the message builder
- ✨ Add local storage and URL support to `Message::file`
- 🔧 Update the default database config
- 🧑‍💻 Add file and line number to the console error output
- ⬆ Bump dependencies
> ✨ Improve the message builder

- src/Services/Service.php
Previously, when an exception appeared in the Service, the application crashed.
This small change fixes this issue. Now, when an exception appears, the console will display a beautiful error message, and the application will continue to work.
> Add a secure call to the handle method
